import 'server-only';

/**
 * M17 v2: 6-part SDXL → 64×64 atlas compositor.
 *
 * Takes one PNG buffer per body part (head, torso, R/L arm, R/L leg)
 * — each generated by an independent Cloudflare SDXL call — and
 * blits each one into all six faces of its corresponding cuboid in
 * the 64×64 Minecraft atlas. The result is a 64×64 RGBA PNG buffer
 * that the existing `generateSkinFromImage` quantize+RLE pipeline
 * then turns into an `AISkinResponse`.
 *
 * The 6 parts were chosen as the natural per-cube unit. We could
 * generate per-face (24+ images for 4 cubes × 6 faces) for higher
 * fidelity, but the cost/latency premium isn't worth it: the back
 * and side faces are barely visible in normal play, and a single
 * source per part still produces correct atlas wrapping. Each
 * part image is resized into all six faces of its cube so the
 * back/sides at least show *something* themed correctly rather
 * than transparent.
 *
 * Why sharp on Vercel and not in the Worker:
 *   - Workers can't run sharp (native binary, ~30MB)
 *   - Workers don't have a built-in image resize / composite API
 *     that handles transparency-preserving lanczos correctly
 *   - The Vercel route already has sharp loaded for the existing
 *     resize+quantize stage, so the marginal cost is zero
 */

import { ImageProcessingError } from './cloudflare-errors';
import {
  BODY_FACES,
  HEAD_FACES,
  LEFT_LEG_FACES,
  RIGHT_LEG_FACES,
  leftArmFaces,
  rightArmFaces,
  type PartFaces,
} from './cloudflare-atlas';

/**
 * Per-part PNG buffers. Each buffer is the raw output of one
 * Cloudflare SDXL Lightning call — typically 512×512 PNG. The
 * compositor handles all resizing.
 */
export type PartImageBuffers = {
  head: Buffer;
  torso: Buffer;
  rightArm: Buffer;
  leftArm: Buffer;
  rightLeg: Buffer;
  leftLeg: Buffer;
  variant: 'classic' | 'slim';
};

const ATLAS_SIZE = 64;

// Sharp module is dynamically imported on first call.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let cachedSharp: any | null = null;

/**
 * Composite 6 part PNGs into a 64×64 Minecraft skin atlas.
 *
 * For each part:
 *   1. Build a list of `{ region, partImage }` pairs covering all
 *      six faces of the cube.
 *   2. For each pair, run sharp.resize → buffer.
 *   3. Add to a single sharp.composite() overlay list.
 *
 * One final 64×64 sharp pipeline composites everything onto a
 * transparent canvas. Returns the PNG buffer.
 *
 * Throws `ImageProcessingError('resize_failed', …)` on sharp
 * failure so the route's existing catch cascade maps to a 422.
 */
export async function compositeSkinAtlas(
  parts: PartImageBuffers,
): Promise<Buffer> {
  const sharp = await loadSharp();

  // (buf, faces) tuples for each body part.
  const partLayouts: Array<{ buf: Buffer; faces: PartFaces; partKey: string }> =
    [
      { buf: parts.head, faces: HEAD_FACES, partKey: 'head' },
      { buf: parts.torso, faces: BODY_FACES, partKey: 'torso' },
      { buf: parts.rightArm, faces: rightArmFaces(parts.variant), partKey: 'rightArm' },
      { buf: parts.leftArm, faces: leftArmFaces(parts.variant), partKey: 'leftArm' },
      { buf: parts.rightLeg, faces: RIGHT_LEG_FACES, partKey: 'rightLeg' },
      { buf: parts.leftLeg, faces: LEFT_LEG_FACES, partKey: 'leftLeg' },
    ];

  // Resize each part image into each of its 6 face dimensions in
  // parallel. Lanczos3 is the right kernel for downscaling photo-
  // grade SDXL output to a 4×12 or 8×8 atlas tile — `nearest`
  // would alias hard, `cubic` blurs.
  const overlays: Array<{ input: Buffer; top: number; left: number }> = [];
  for (const { buf, faces, partKey } of partLayouts) {
    const allFaces = [
      faces.front, // paint front first so it wins z-order if any face overlaps (none should)
      faces.back,
      faces.left,
      faces.right,
      faces.top,
      faces.bottom,
    ];
    for (const region of allFaces) {
      let resized: Buffer;
      try {
        resized = await sharp(buf)
          .resize(region.w, region.h, { kernel: 'lanczos3', fit: 'fill' })
          .ensureAlpha()
          .png()
          .toBuffer();
      } catch (err) {
        throw new ImageProcessingError(
          'resize_failed',
          `failed to resize ${partKey} for region ${region.x},${region.y}: ${formatErr(err)}`,
        );
      }
      overlays.push({ input: resized, top: region.y, left: region.x });
    }
  }

  // Build 64×64 fully-transparent canvas and composite every face.
  let atlasBuf: Buffer;
  try {
    atlasBuf = await sharp({
      create: {
        width: ATLAS_SIZE,
        height: ATLAS_SIZE,
        channels: 4,
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      },
    })
      .composite(overlays)
      .png()
      .toBuffer();
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `failed to composite atlas: ${formatErr(err)}`,
    );
  }

  return atlasBuf;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function loadSharp(): Promise<any> {
  if (cachedSharp !== null) return cachedSharp;
  try {
    const mod = await import('sharp');
    const callable =
      typeof mod === 'function'
        ? mod
        : typeof (mod as { default?: unknown }).default === 'function'
          ? (mod as { default: (b: Buffer | object) => unknown }).default
          : null;
    if (callable === null) {
      throw new Error('sharp default export is not callable');
    }
    cachedSharp = callable;
    return callable;
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `failed to load sharp: ${formatErr(err)}`,
    );
  }
}

function formatErr(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === 'string') return err;
  return 'unknown sharp error';
}
