import 'server-only';

/**
 * M17 v2.1: 6-part SDXL → 64×64 atlas compositor.
 *
 * Takes one PNG buffer per body part (head, torso, R/L arm, R/L leg)
 * — each generated by an independent Cloudflare SDXL call — and
 * blits each one into the canonical Minecraft 1.8+ atlas layout. The
 * result is a 64×64 RGBA PNG buffer that the existing
 * `generateSkinFromImage` quantize+RLE pipeline turns into an
 * `AISkinResponse`.
 *
 * FACE TREATMENT
 * ──────────────
 * Per-face strategy was chosen to match how real Minecraft skins are
 * authored AND to fight three failure modes observed during M17 v2:
 *
 * 1. "Tiled face" pattern — when every face of a cube is the same
 *    SDXL render, the atlas looks like 6 mini-helmets tiled in a
 *    row. The 3D model reads as a multi-faced creature.
 * 2. White-background bleed — SDXL outputs have a plain (white-ish)
 *    background around the centered subject; resizing the full
 *    512×512 stretches that background into the face rectangle.
 * 3. Anti-aliased mush — `kernel: 'lanczos3'` blurs hard edges into
 *    grays, which the editor's nearest-neighbor 3D shader then
 *    enlarges into smudgy clusters.
 *
 * The per-face rules:
 *   - FRONT: center-cropped SDXL source, resized with `kernel: 'nearest'`
 *           for crisp blocks. This is the one detailed face on each cube.
 *   - BACK:  horizontally-mirrored center-crop, also nearest-resized.
 *           Matches the visual "back of a Minecraft skin" convention
 *           (often a flipped version of the front).
 *   - LEFT, RIGHT, TOP, BOTTOM: solid sampled color drawn from the
 *           center of the source. This gives a thematically-correct
 *           silhouette on the 3D model without the tiled-face artifact.
 *
 * Why sharp on Vercel and not in the Worker:
 *   - Workers can't run sharp (native binary, ~30MB)
 *   - Workers don't have a built-in lanczos / nearest resize API
 *   - The Vercel route already has sharp loaded for the existing
 *     resize+quantize stage, so the marginal cost is zero
 */

import { ImageProcessingError } from './cloudflare-errors';
import {
  BODY_FACES,
  HEAD_FACES,
  LEFT_LEG_FACES,
  RIGHT_LEG_FACES,
  leftArmFaces,
  rightArmFaces,
  type AtlasRegion,
  type PartFaces,
} from './cloudflare-atlas';

export type PartImageBuffers = {
  head: Buffer;
  torso: Buffer;
  rightArm: Buffer;
  leftArm: Buffer;
  rightLeg: Buffer;
  leftLeg: Buffer;
  variant: 'classic' | 'slim';
};

const ATLAS_SIZE = 64;

/**
 * Center-crop fraction. The SDXL output is a centered subject on a
 * plain background; cropping to 60% × 60% of the source drops most
 * of the background while keeping the full body part in frame.
 */
const CENTER_CROP_FRACTION = 0.6;

/** Sampling region for "dominant color" — the very center of the source. */
const SAMPLE_FRACTION = 0.4;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Sharp = any;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let cachedSharp: any | null = null;

type Overlay = { input: Buffer; top: number; left: number };

export async function compositeSkinAtlas(
  parts: PartImageBuffers,
): Promise<Buffer> {
  const sharp = await loadSharp();

  const partLayouts: Array<{ buf: Buffer; faces: PartFaces; partKey: string }> =
    [
      { buf: parts.head, faces: HEAD_FACES, partKey: 'head' },
      { buf: parts.torso, faces: BODY_FACES, partKey: 'torso' },
      { buf: parts.rightArm, faces: rightArmFaces(parts.variant), partKey: 'rightArm' },
      { buf: parts.leftArm, faces: leftArmFaces(parts.variant), partKey: 'leftArm' },
      { buf: parts.rightLeg, faces: RIGHT_LEG_FACES, partKey: 'rightLeg' },
      { buf: parts.leftLeg, faces: LEFT_LEG_FACES, partKey: 'leftLeg' },
    ];

  const overlays: Overlay[] = [];
  for (const { buf, faces, partKey } of partLayouts) {
    const partOverlays = await buildPartOverlays(sharp, buf, faces, partKey);
    overlays.push(...partOverlays);
  }

  let atlasBuf: Buffer;
  try {
    atlasBuf = await sharp({
      create: {
        width: ATLAS_SIZE,
        height: ATLAS_SIZE,
        channels: 4,
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      },
    })
      .composite(overlays)
      .png()
      .toBuffer();
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `failed to composite atlas: ${formatErr(err)}`,
    );
  }
  return atlasBuf;
}

/**
 * Build the 6 face overlays for a single body part. See file header
 * comment for the per-face strategy.
 */
async function buildPartOverlays(
  sharp: Sharp,
  buf: Buffer,
  faces: PartFaces,
  partKey: string,
): Promise<Overlay[]> {
  // Prep — decode the source once, derive everything else from it.
  let meta: { width: number; height: number };
  try {
    const m = await sharp(buf).metadata();
    if (typeof m.width !== 'number' || typeof m.height !== 'number') {
      throw new Error('source PNG missing dimensions');
    }
    meta = { width: m.width, height: m.height };
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `metadata failed for ${partKey}: ${formatErr(err)}`,
    );
  }

  // Pre-cropped centered region used as the source for FRONT and BACK.
  // Drops the white background that SDXL leaves around the subject.
  const cropW = Math.max(1, Math.floor(meta.width * CENTER_CROP_FRACTION));
  const cropH = Math.max(1, Math.floor(meta.height * CENTER_CROP_FRACTION));
  const cropLeft = Math.floor((meta.width - cropW) / 2);
  const cropTop = Math.floor((meta.height - cropH) / 2);

  // Dominant color sampled from the very center of the source —
  // tighter than the front-crop so the average isn't pulled toward
  // the silhouette edges.
  const sampleW = Math.max(1, Math.floor(meta.width * SAMPLE_FRACTION));
  const sampleH = Math.max(1, Math.floor(meta.height * SAMPLE_FRACTION));
  const sampleLeft = Math.floor((meta.width - sampleW) / 2);
  const sampleTop = Math.floor((meta.height - sampleH) / 2);

  let dominant: { r: number; g: number; b: number };
  try {
    const stats = await sharp(buf)
      .extract({ left: sampleLeft, top: sampleTop, width: sampleW, height: sampleH })
      .stats();
    const channels = stats.channels ?? [];
    dominant = {
      r: clampByte(channels[0]?.mean ?? 128),
      g: clampByte(channels[1]?.mean ?? 128),
      b: clampByte(channels[2]?.mean ?? 128),
    };
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `dominant-color sample failed for ${partKey}: ${formatErr(err)}`,
    );
  }

  return [
    await buildFrontOverlay(sharp, buf, faces.front, cropLeft, cropTop, cropW, cropH, partKey, false),
    await buildFrontOverlay(sharp, buf, faces.back, cropLeft, cropTop, cropW, cropH, partKey, true),
    await buildSolidOverlay(sharp, faces.left, dominant, partKey),
    await buildSolidOverlay(sharp, faces.right, dominant, partKey),
    await buildSolidOverlay(sharp, faces.top, dominant, partKey),
    await buildSolidOverlay(sharp, faces.bottom, dominant, partKey),
  ];
}

/**
 * Resize the centered crop of the source PNG into the face rectangle
 * with nearest-neighbor scaling for crisp pixel-art blocks. `flop`
 * mirrors horizontally — used for the back face.
 */
async function buildFrontOverlay(
  sharp: Sharp,
  buf: Buffer,
  region: AtlasRegion,
  cropLeft: number,
  cropTop: number,
  cropW: number,
  cropH: number,
  partKey: string,
  mirror: boolean,
): Promise<Overlay> {
  try {
    let pipeline = sharp(buf).extract({
      left: cropLeft,
      top: cropTop,
      width: cropW,
      height: cropH,
    });
    if (mirror) pipeline = pipeline.flop();
    const resized = await pipeline
      .resize(region.w, region.h, { kernel: 'nearest', fit: 'fill' })
      .ensureAlpha()
      .png()
      .toBuffer();
    return { input: resized, top: region.y, left: region.x };
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `front/back overlay failed for ${partKey}: ${formatErr(err)}`,
    );
  }
}

/**
 * Generate a solid-color rectangle of `region.w × region.h` filled
 * with the sampled dominant color. Used for left/right/top/bottom
 * faces so the 3D silhouette stays color-themed without showing a
 * tiled copy of the front render.
 */
async function buildSolidOverlay(
  sharp: Sharp,
  region: AtlasRegion,
  color: { r: number; g: number; b: number },
  partKey: string,
): Promise<Overlay> {
  try {
    const buf = await sharp({
      create: {
        width: region.w,
        height: region.h,
        channels: 4,
        background: { r: color.r, g: color.g, b: color.b, alpha: 1 },
      },
    })
      .png()
      .toBuffer();
    return { input: buf, top: region.y, left: region.x };
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `solid overlay failed for ${partKey}: ${formatErr(err)}`,
    );
  }
}

function clampByte(n: number): number {
  if (!Number.isFinite(n)) return 128;
  return Math.max(0, Math.min(255, Math.round(n)));
}

async function loadSharp(): Promise<Sharp> {
  if (cachedSharp !== null) return cachedSharp;
  try {
    const mod = await import('sharp');
    const callable =
      typeof mod === 'function'
        ? mod
        : typeof (mod as { default?: unknown }).default === 'function'
          ? (mod as { default: (b: Buffer | object) => unknown }).default
          : null;
    if (callable === null) {
      throw new Error('sharp default export is not callable');
    }
    cachedSharp = callable;
    return callable;
  } catch (err) {
    throw new ImageProcessingError(
      'resize_failed',
      `failed to load sharp: ${formatErr(err)}`,
    );
  }
}

function formatErr(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === 'string') return err;
  return 'unknown sharp error';
}
